[package]
name = "swc-wasi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swc = "0.120.0"
swc_ecma_minifier = "0.71.4"
swc_ecmascript = "0.111.10"

[profile.release]
lto = true
opt-level = "s"
